// priority: 2
const SkyeItems = {
  simpleCollections: {
    util: [
      'moa_decor_electronics:aire_acondicionado',
      'moa_decor_electronics:aire_acondicionado_moderno',
      'moa_decor_electronics:camara_seguridad_derecha',
      'moa_decor_electronics:camara_seguridad_frontal',
      'moa_decor_electronics:camara_seguridad_izquierda',
      'moa_decor_electronics:rejilla_ventilacion',
    ],
    consoles: [
      'moa_decor_electronics:c_atari_2600',
      'moa_decor_electronics:c_dream_cast',
      'moa_decor_electronics:c_game_boy',
      'moa_decor_electronics:c_game_cube',
      'moa_decor_electronics:c_mega_drive',
      'moa_decor_electronics:c_nintendo_64',
      'moa_decor_electronics:c_nintendo_ds',
      'moa_decor_electronics:c_nintendo_super_famicom',
      'moa_decor_electronics:c_nintendo_switch',
      'moa_decor_electronics:c_nintendo_wii',
      'moa_decor_electronics:c_nintendo_wii_u',
      'moa_decor_electronics:c_playstation_1',
      'moa_decor_electronics:c_playstation_2',
      'moa_decor_electronics:c_playstation_3',
      'moa_decor_electronics:c_playstation_4',
      'moa_decor_electronics:c_playstation_5',
      'moa_decor_electronics:c_xbox',
      'moa_decor_electronics:c_xbox_360',
      'moa_decor_electronics:c_xbox_one',
      'moa_decor_electronics:c_xbox_series_s',
      'moa_decor_electronics:c_xbox_series_x',
      'moa_decor_electronics:cnes',
      'moa_decor_electronics:cpsp',
    ],
    laptops: [
      'moa_decor_electronics:laptop_blanca',
      'moa_decor_electronics:laptop_blanca_codigo',
      'moa_decor_electronics:laptop_blanca_minecraft',
      'moa_decor_electronics:laptop_blanca_noticiero',
      'moa_decor_electronics:laptop_blanca_pollo',
      'moa_decor_electronics:laptop_blanca_youtube',
      'moa_decor_electronics:laptop_gris',
      'moa_decor_electronics:laptop_gris_codigo',
      'moa_decor_electronics:laptop_gris_minecraft',
      'moa_decor_electronics:laptop_gris_noticiero',
      'moa_decor_electronics:laptop_gris_pollo',
      'moa_decor_electronics:laptop_gris_youtube',
      'moa_decor_electronics:laptop_negra',
      'moa_decor_electronics:laptop_negra_codigo',
      'moa_decor_electronics:laptop_negra_minecraft',
      'moa_decor_electronics:laptop_negra_noticiero',
      'moa_decor_electronics:laptop_negra_pollo',
      'moa_decor_electronics:laptop_negra_youtube',
    ],
    office: [
      'moa_decor_electronics:impresora',
      'moa_decor_electronics:pc_antigua',
      'moa_decor_electronics:pc_antigua_encendida',
      'moa_decor_electronics:teclado_antiguo',
    ],
    pcs: [
      'moa_decor_electronics:pc_gamer_amarilla',
      'moa_decor_electronics:pc_gamer_azul',
      'moa_decor_electronics:pc_gamer_azul_clara',
      'moa_decor_electronics:pc_gamer_blanca',
      'moa_decor_electronics:pc_gamer_cafe',
      'moa_decor_electronics:pc_gamer_cian',
      'moa_decor_electronics:pc_gamer_gris',
      'moa_decor_electronics:pc_gamer_gris_clara',
      'moa_decor_electronics:pc_gamer_magenta',
      'moa_decor_electronics:pc_gamer_morada',
      'moa_decor_electronics:pc_gamer_naranja',
      'moa_decor_electronics:pc_gamer_negra',
      'moa_decor_electronics:pc_gamer_rojo',
      'moa_decor_electronics:pc_gamer_rosa',
      'moa_decor_electronics:pc_gamer_verde',
      'moa_decor_electronics:pc_gamer_verde_lima',
    ],
    monitors: [
      'moa_decor_electronics:teclado_monitor',
      'moa_decor_electronics:teclado_monitor_codigo',
      'moa_decor_electronics:teclado_monitor_minecraft',
      'moa_decor_electronics:teclado_monitor_noticiero',
      'moa_decor_electronics:teclado_monitor_pollo',
      'moa_decor_electronics:teclado_monitor_youtube',
    ],
    alarmClocks: [
      'moa_decor_electronics:reloj_despertador_amarillo',
      'moa_decor_electronics:reloj_despertador_azul',
      'moa_decor_electronics:reloj_despertador_azul_claro',
      'moa_decor_electronics:reloj_despertador_blanco',
      'moa_decor_electronics:reloj_despertador_cafe',
      'moa_decor_electronics:reloj_despertador_cian',
      'moa_decor_electronics:reloj_despertador_gris',
      'moa_decor_electronics:reloj_despertador_gris_claro',
      'moa_decor_electronics:reloj_despertador_magenta',
      'moa_decor_electronics:reloj_despertador_morado',
      'moa_decor_electronics:reloj_despertador_naranja',
      'moa_decor_electronics:reloj_despertador_negro',
      'moa_decor_electronics:reloj_despertador_rojo',
      'moa_decor_electronics:reloj_despertador_rosa',
      'moa_decor_electronics:reloj_despertador_verde',
      'moa_decor_electronics:reloj_despertador_verde_lima',
    ],
    phones: [
      'moa_decor_electronics:telefono_antiguo_amarillo',
      'moa_decor_electronics:telefono_antiguo_azul',
      'moa_decor_electronics:telefono_antiguo_azul_claro',
      'moa_decor_electronics:telefono_antiguo_blanco',
      'moa_decor_electronics:telefono_antiguo_cafe',
      'moa_decor_electronics:telefono_antiguo_cian',
      'moa_decor_electronics:telefono_antiguo_gris',
      'moa_decor_electronics:telefono_antiguo_gris_claro',
      'moa_decor_electronics:telefono_antiguo_magenta',
      'moa_decor_electronics:telefono_antiguo_morado',
      'moa_decor_electronics:telefono_antiguo_naranja',
      'moa_decor_electronics:telefono_antiguo_negro',
      'moa_decor_electronics:telefono_antiguo_rojo',
      'moa_decor_electronics:telefono_antiguo_rosa',
      'moa_decor_electronics:telefono_antiguo_verde',
      'moa_decor_electronics:telefono_antiguo_verde_lima',
    ],
    flatTv: [
      'moa_decor_electronics:tv',
      'moa_decor_electronics:tv_minecraft',
      'moa_decor_electronics:tv_netflix',
      'moa_decor_electronics:tv_noticiero',
      'moa_decor_electronics:tv_pollo',
    ]
  },
  listCollections: null,
}