const FishInfo = {
  weights: [
    { name: "tide:deep_grouper", weight: 90 },
    { name: "tide:shadow_snapper", weight: 90 },
    { name: "tide:luminescent_jellyfish", weight: 70 },
    { name: "tide:abyss_angler", weight: 70 },
    { name: "tide:lapis_lanternfish", weight: 50 },
    { name: "tide:crystalline_carp", weight: 40 },
    { name: "tide:bedrock_tetra", weight: 30 },
    { name: "tide:trout", weight: 100 },
    { name: "minecraft:salmon", weight: 90 },
    { name: "tide:yellow_perch", weight: 85 },
    { name: "tide:bluegill", weight: 80 },
    { name: "tide:pike", weight: 50 },
    { name: "tide:catfish", weight: 25 },
    { name: "tide:clayfish", weight: 18 },
    { name: "tide:bass", weight: 15 },
    { name: "tide:mint_carp", weight: 10 },
    { name: "tide:bass", weight: 95 },
    { name: "tide:bluegill", weight: 80 },
    { name: "tide:trout", weight: 80 },
    { name: "tide:yellow_perch", weight: 80 },
    { name: "minecraft:salmon", weight: 75 },
    { name: "tide:mint_carp", weight: 50 },
    { name: "tide:guppy", weight: 20 },
    { name: "tide:pike", weight: 20 },
    { name: "tide:catfish", weight: 15 },
    { name: "tide:clayfish", weight: 12 },
    { name: "tide:bass", weight: 95 },
    { name: "tide:mint_carp", weight: 90 },
    { name: "tide:guppy", weight: 80 },
    { name: "minecraft:salmon", weight: 65 },
    { name: "tide:yellow_perch", weight: 50 },
    { name: "tide:bluegill", weight: 40 },
    { name: "tide:guppy", weight: 40 },
    { name: "tide:trout", weight: 35 },
    { name: "tide:pike", weight: 20 },
    { name: "tide:clayfish", weight: 8 },
    { name: "tide:fish_bone", weight: 20 },
    { name: "tide:ember_koi", weight: 40 },
    { name: "tide:inferno_guppy", weight: 30 },
    { name: "tide:obsidian_pike", weight: 35 },
    { name: "tide:volcano_tuna", weight: 20 },
    { name: "tide:obsidian_fragment", weight: 60 },
    { name: "tide:fish_bone", weight: 40 },
    { name: "tide:ember_koi", weight: 40 },
    { name: "tide:inferno_guppy", weight: 30 },
    { name: "tide:obsidian_pike", weight: 25 },
    { name: "tide:volcano_tuna", weight: 8 },
    { name: "tide:obsidian_fragment", weight: 60 },
    { name: "tide:fish_bone", weight: 30 },
    { name: "tide:ember_koi", weight: 40 },
    { name: "tide:inferno_guppy", weight: 30 },
    { name: "tide:obsidian_pike", weight: 25 },
    { name: "tide:volcano_tuna", weight: 10 },
    { name: "minecraft:cod", weight: 100 },
    { name: "tide:ocean_perch", weight: 80 },
    { name: "minecraft:salmon", weight: 60 },
    { name: "tide:trout", weight: 45 },
    { name: "tide:tuna", weight: 25 },
    { name: "minecraft:cod", weight: 100 },
    { name: "tide:mackerel", weight: 70 },
    { name: "minecraft:salmon", weight: 60 },
    { name: "tide:ocean_perch", weight: 50 },
    { name: "tide:trout", weight: 25 },
    { name: "tide:tuna", weight: 20 },
    { name: "minecraft:pufferfish", weight: 15 },
    { name: "tide:barracuda", weight: 8 },
    { name: "tide:sailfish", weight: 5 },
    { name: "minecraft:tropical_fish", weight: 70 },
    { name: "tide:tuna", weight: 45 },
    { name: "tide:mackerel", weight: 40 },
    { name: "minecraft:pufferfish", weight: 35 },
    { name: "tide:angelfish", weight: 30 },
    { name: "minecraft:cod", weight: 25 },
    { name: "tide:sailfish", weight: 15 },
    { name: "tide:barracuda", weight: 15 },
    { name: "tide:cave_eel", weight: 90 },
    { name: "tide:cave_crawler", weight: 90 },
    { name: "tide:glowfish", weight: 70 },
    { name: "tide:anglerfish", weight: 70 },
    { name: "tide:iron_tetra", weight: 50 },
    { name: "tide:crystal_shrimp", weight: 30 },
    { name: "tide:gilded_minnow", weight: 10 }
  ],
  specialFishes: [
    "tide:blossom_bass",
    "tide:echofin_snapper",
    "tide:dripstone_darter",
    "tide:fluttergill",
    "tide:sunspike_goby",
    "tide:birch_trout",
    "tide:mirage_catfish",
    "tide:slimefin_snapper",
    "tide:sporestalker",
    "tide:leafback",
    "tide:pine_perch",
    "tide:sandskipper",
    "tide:stonefish",
    "tide:frostbite_flounder",
    "tide:oakfish",
    "tide:prarie_pike"
  ]
}