const FishInfo = {
  weights: {
    "minecraft:cod": 100,
    "minecraft:pufferfish": 35,
    "minecraft:salmon": 90,
    "minecraft:tropical_fish": 70,
    "tide:abyss_angler": 70,
    "tide:angelfish": 30,
    "tide:anglerfish": 70,
    "tide:barracuda": 15,
    "tide:bass": 95,
    "tide:bedrock_tetra": 30,
    "tide:bluegill": 80,
    "tide:catfish": 25,
    "tide:cave_crawler": 90,
    "tide:cave_eel": 90,
    "tide:clayfish": 18,
    "tide:crystal_shrimp": 30,
    "tide:crystalline_carp": 40,
    "tide:deep_grouper": 90,
    "tide:ember_koi": 40,
    "tide:gilded_minnow": 10,
    "tide:glowfish": 70,
    "tide:guppy": 80,
    "tide:inferno_guppy": 30,
    "tide:iron_tetra": 50,
    "tide:lapis_lanternfish": 50,
    "tide:luminescent_jellyfish": 70,
    "tide:mackerel": 70,
    "tide:mint_carp": 90,
    "tide:ocean_perch": 80,
    "tide:pike": 50,
    "tide:sailfish": 15,
    "tide:shadow_snapper": 90,
    "tide:trout": 100,
    "tide:tuna": 45,
    "tide:volcano_tuna": 20,
    "tide:yellow_perch": 85
  },
  specialFishes: [
    "tide:blossom_bass",
    "tide:echofin_snapper",
    "tide:dripstone_darter",
    "tide:fluttergill",
    "tide:sunspike_goby",
    "tide:birch_trout",
    "tide:mirage_catfish",
    "tide:slimefin_snapper",
    "tide:sporestalker",
    "tide:leafback",
    "tide:pine_perch",
    "tide:sandskipper",
    "tide:stonefish",
    "tide:frostbite_flounder",
    "tide:oakfish",
    "tide:prarie_pike"
  ]
}