RequestHandler.tooltips.add([
  [
    [
      'advancednetherite:netherite_diamond_ingot',
      'advancednetherite:netherite_emerald_ingot',
      'advancednetherite:netherite_gold_ingot',
      'advancednetherite:netherite_iron_ingot',
    ],
    [
      Text.translate('tutorialsHints.advancedNetherite1'),
      Text.translate('tutorialsHints.advancedNetherite2')
    ]
  ]
])