// priority: 2
const PinguItems = {
  onaulDiscs: [
    "kubejs:oneul_april_daisy",
    "kubejs:oneul_around_midnight",
    "kubejs:oneul_autumn_blessing",
    "kubejs:oneul_autumn_breeze",
    "kubejs:oneul_brunch",
    "kubejs:oneul_bubble",
    "kubejs:oneul_byesummer",
    "kubejs:oneul_canele",
    "kubejs:oneul_cheeseburger",
    "kubejs:oneul_chestnut_latte",
    "kubejs:oneul_chocolate_world",
    "kubejs:oneul_chuseok",
    "kubejs:oneul_cloudy_rain",
    "kubejs:oneul_cookie_tree",
    "kubejs:oneul_dreamy",
    "kubejs:oneul_flamingo",
    "kubejs:oneul_floating_marshmallow",
    "kubejs:oneul_full_moon",
    "kubejs:oneul_get_up",
    "kubejs:oneul_gift",
    "kubejs:oneul_happy_reindeer",
    "kubejs:oneul_joy",
    "kubejs:oneul_melon_bread",
    "kubejs:oneul_miracle_morning",
    "kubejs:oneul_mistletoe",
    "kubejs:oneul_moonlight",
    "kubejs:oneul_morning_peppermint",
    "kubejs:oneul_painting",
    "kubejs:oneul_pajama",
    "kubejs:oneul_raindrops",
    "kubejs:oneul_roommate",
    "kubejs:oneul_sandwich",
    "kubejs:oneul_smile_peach",
    "kubejs:oneul_snow_dance",
    "kubejs:oneul_story",
    "kubejs:oneul_strawberry_dance",
    "kubejs:oneul_summer_vacation",
    "kubejs:oneul_surf",
    "kubejs:oneul_tiramisu",
    "kubejs:oneul_umbrella",
    "kubejs:oneul_vanilla_milkshake",
    "kubejs:oneul_watermelon_fizz",
    "kubejs:oneul_weekend_blanket",
    "kubejs:oneul_winter_glow",
  ],
  minecraftDiscs: [
    "minecraft:music_disc_11",
    "minecraft:music_disc_13",
    "minecraft:music_disc_5",
    "minecraft:music_disc_blocks",
    "minecraft:music_disc_cat",
    "minecraft:music_disc_chirp",
    "minecraft:music_disc_creator",
    "minecraft:music_disc_creator_music_box",
    "minecraft:music_disc_far",
    "minecraft:music_disc_mall",
    "minecraft:music_disc_mellohi",
    "minecraft:music_disc_otherside",
    "minecraft:music_disc_pigstep",
    "minecraft:music_disc_precipice",
    "minecraft:music_disc_relic",
    "minecraft:music_disc_stal",
    "minecraft:music_disc_strad",
    "minecraft:music_disc_wait",
    "minecraft:music_disc_ward",
  ],
  otherDiscs: [
    "beachparty:overgrown_disc",
    "beachparty:music_disc_beachparty",
    "beachparty:music_disc_caribbean_beach",
    "beachparty:music_disc_pridelands",
    "beachparty:music_disc_vocalista",
    "beachparty:music_disc_wild_veins",
    "sophisticatedstorage:advanced_jukebox_upgrade",
    "furniture:cphs_pride",
    "furniture:letsdo_theme",
    "create_confectionery:the_bright_side",
    "biomeswevegone:music_disc_pixie_club",
    "biomeswevegone:music_disc_better_days",
    "betterarcheology:music_disc_swings",
  ],
  musicPlayers: [
    "minecraft:jukebox",
    "furniture:gramophone",
  ],
  musicUpgrades: [
    "sophisticatedstorage:advanced_jukebox_upgrade",
    "sophisticatedbackpacks:advanced_jukebox_upgrade",
  ],
  skyPenguinDiscs: [
    'kubejs:sky_penguin_midnight_frankum',
    'kubejs:sky_penguin_stargazing_frankum',
    'kubejs:sky_penguin_sunrise_frankum',
    'kubejs:sky_penguin_together_migfus20',
  ],
  get allItems () {
    return this.minecraftDiscs.concat(
      this.otherDiscs,
      this.onaulDiscs,
      this.musicPlayers,
      this.musicUpgrades,
      this.skyPenguinDiscs
    )
  }
}
