from botany_pots import keys

seedDefs = [
  {
    keys.seed: 'farm_and_charm:kernels',
    keys.crop: 'farm_and_charm:corn',
    keys.block: 'farm_and_charm:corn_crop'
  }, {
    keys.seed: 'farm_and_charm:oat_seeds',
    keys.crop: 'farm_and_charm:oat',
    keys.block: 'farm_and_charm:oat_crop'
  }, {
    keys.seed: 'farm_and_charm:barley_seeds',
    keys.crop: 'farm_and_charm:barley',
    keys.block: 'farm_and_charm:barley_crop'
  }, {
    keys.seed: 'farm_and_charm:lettuce_seeds',
    keys.crop: 'farm_and_charm:lettuce',
    keys.block: 'farm_and_charm:lettuce_crop'
  }, {
    keys.seed: 'farm_and_charm:onion',
    keys.crop: 'farm_and_charm:onion',
    keys.block: 'farm_and_charm:onion_crop'
  }, {
    keys.seed: 'farm_and_charm:tomato_seeds',
    keys.crop: 'farm_and_charm:tomato',
    keys.block: 'farm_and_charm:tomato_crop'
  }, {
    keys.seed: 'farm_and_charm:strawberry_seeds',
    keys.crop: 'farm_and_charm:strawberry',
    keys.block: 'farm_and_charm:strawberry_crop'
  }, {
		keys.seed: 'vinery:jungle_grape_seeds_red',
		keys.crop: 'vinery:jungle_grapes_red',
		keys.block: 'vinery:jungle_grape_bush_red'
	}, {
		keys.seed: 'vinery:jungle_grape_seeds_white',
		keys.crop: 'vinery:jungle_grapes_white',
		keys.block: 'vinery:jungle_grape_bush_white'
	}, {
		keys.seed: 'vinery:red_grape_seeds',
		keys.crop: 'vinery:red_grape',
		keys.block: 'vinery:red_grape_bush'
	}, {
		keys.seed: 'vinery:savanna_grape_seeds_red',
		keys.crop: 'vinery:savanna_grapes_red',
		keys.block: 'vinery:savanna_grape_bush_red'
	}, {
		keys.seed: 'vinery:savanna_grape_seeds_white',
		keys.crop: 'vinery:savanna_grapes_white',
		keys.block: 'vinery:savanna_grape_bush_white'
	}, {
		keys.seed: 'vinery:taiga_grape_seeds_red',
		keys.crop: 'vinery:taiga_grapes_red',
		keys.block: 'vinery:taiga_grape_bush_red'
	}, {
		keys.seed: 'vinery:taiga_grape_seeds_white',
		keys.crop: 'vinery:taiga_grapes_white',
		keys.block: 'vinery:taiga_grape_bush_white'
	}, {
		keys.seed: 'vinery:white_grape_seeds',
		keys.crop: 'vinery:white_grape',
		keys.block: 'vinery:white_grape_bush'
	}, {
		keys.seed: "vinery:dark_cherry_sapling",
		keys.crop: "vinery:cherry",
		keys.block: "vinery:dark_cherry_sapling"
  }, {
		keys.seed: "vinery:apple_tree_sapling",
		keys.crop: "minecraft:apple",
		keys.block: "vinery:apple_tree_sapling"
  }, {
		keys.seed: "beachparty:palm_sprout",
		keys.crop: "beachparty:coconut",
		keys.block: "beachparty:palm_sprout"
  }, {
    keys.seed: "brewery:hops_seeds",
    keys.crop: "brewery:hops",
		keys.block: "brewery:hops_crop"
  }, {
    keys.seed: "brewery:corn_seeds",
    keys.crop: "brewery:corn",
		keys.block: "brewery:corn_crop"
  }, {
		keys.seed: "herbalbrews:tea_blossom",
		keys.crop: "herbalbrews:green_tea_leaf",
		keys.block: "herbalbrews:tea_plant"
  }, {
		keys.seed: "herbalbrews:yerba_mate_leaf",
		keys.crop: "herbalbrews:yerba_mate_leaf",
		keys.block: "herbalbrews:yerba_mate_plant"
  }, {
		keys.seed: "herbalbrews:rooibos_leaf",
		keys.crop: "herbalbrews:rooibos_leaf",
		keys.block: "herbalbrews:rooibos_plant"
  }, {
		keys.seed: "herbalbrews:coffee_beans",
		keys.crop: "herbalbrews:coffee_beans",
		keys.block: "herbalbrews:coffee_plant"
  }, {
    keys.seed: 'minecraft:blaze_powder',
    keys.crop: 'minecraft:blaze_rod',
    keys.block: 'minecraft:lightning_rod'
	}
]