ItemEvents.modifyTooltips(event => {
  event.add(
    [
      'minecraft:cod', 
      'minecraft:tropical_fish', 
      'minecraft:salmon', 
      'minecraft:pufferfish'
    ],
    [
      Text.translate('collectionTooltips.aquarium'), 
      Text.translate('collectionTooltips.vanillaCompletion')
    ])
  event.add(
    [
      'tide:bass', 
      'tide:bluegill', 
      'tide:catfish', 
      'tide:clayfish', 
      'tide:guppy', 
      'tide:mint_carp', 
      'tide:pike', 
      'tide:yellow_perch'
    ],
    [
      Text.translate('collectionTooltips.aquarium'), 
      Text.translate('collectionTooltips.freshwaterCompletion')
    ])
  event.add(
    [
      'tide:angelfish', 
      'tide:barracuda', 
      'tide:mackerel', 
      'tide:ocean_perch', 
      'tide:sailfish', 
      'tide:trout', 
      'tide:tuna'
    ],
    [
      Text.translate('collectionTooltips.aquarium'), 
      Text.translate('collectionTooltips.saltwaterCompletion')
    ])
  event.add(
    [
      'tide:deep_grouper', 
      'tide:shadow_snapper', 
      'tide:luminescent_jellyfish', 
      'tide:abyss_angler', 
      'tide:lapis_lanternfish', 
      'tide:crystalline_carp', 
      'tide:bedrock_tetra', 
      'tide:ember_koi', 
      'tide:inferno_guppy', 
      'tide:obsidian_pike', 
      'tide:volcano_tuna', 
      'tide:cave_eel', 
      'tide:cave_crawler', 
      'tide:glowfish', 
      'tide:anglerfish', 
      'tide:iron_tetra', 
      'tide:crystal_shrimp', 
      'tide:gilded_minnow'
    ],
    [
      Text.translate('collectionTooltips.aquarium'), 
      Text.translate('collectionTooltips.alternativeLocalesCompletion')
    ])
  event.add(
    [
      'tide:blossom_bass', 
      'tide:echofin_snapper', 
      'tide:dripstone_darter', 
      'tide:fluttergill', 
      'tide:sunspike_goby', 
      'tide:birch_trout', 
      'tide:mirage_catfish', 
      'tide:slimefin_snapper', 
      'tide:sporestalker', 
      'tide:leafback', 
      'tide:pine_perch', 
      'tide:sandskipper', 
      'tide:stonefish', 
      'tide:frostbite_flounder', 
      'tide:oakfish', 
      'tide:prarie_pike'
    ],
    [
      Text.translate('collectionTooltips.aquarium'), 
      Text.translate('collectionTooltips.specialCompletion')
    ])

})