ItemEvents.modifyTooltips(event => {
  event.add(
    [
      'tide:arapaima', 
      'tide:black_crappie', 
      'tide:blossom_bass', 
      'tide:bluegill', 
      'tide:brook_trout', 
      'tide:bull_shark', 
      'tide:carp', 
      'tide:catfish', 
      'tide:frostbite_flounder', 
      'tide:guppy', 
      'tide:largemouth_bass', 
      'tide:mirage_catfish', 
      'tide:mooneye', 
      'tide:pike', 
      'tide:rainbow_trout', 
      'tide:sand_tiger_shark', 
      'tide:slimy_salmon', 
      'tide:smallmouth_bass', 
      'tide:sturgeon', 
      'tide:walleye', 
      'tide:white_crappie', 
      'tide:yellow_perch', 
      'minecraft:salmon'
    ],
    [
      Text.translate('collectionTooltips.aquarium'), 
      Text.translate('collectionTooltips.freshwaterCompletion')
    ])
  event.add(
    [
      'tide:anchovy', 
      'tide:angelfish', 
      'tide:aquathorn', 
      'tide:coelacanth', 
      'tide:flounder', 
      'tide:great_white_shark', 
      'tide:mackerel', 
      'tide:mahi_mahi', 
      'tide:manta_ray', 
      'tide:marstilus', 
      'tide:neptune_koi', 
      'tide:ocean_perch', 
      'tide:pluto_snail', 
      'tide:red_snapper', 
      'tide:sailfish', 
      'tide:saturn_cuttlefish', 
      'tide:shooting_starfish', 
      'tide:snook', 
      'tide:spore_stalker', 
      'tide:sun_emblem', 
      'tide:swordfish', 
      'tide:tuna', 
      'tide:uranias_pisces', 
      'minecraft:cod', 
      'minecraft:pufferfish', 
      'minecraft:tropical_fish'
    ],
    [
      Text.translate('collectionTooltips.aquarium'), 
      Text.translate('collectionTooltips.saltwaterCompletion')
    ])
  event.add(
    [
      'tide:abyss_angler', 
      'tide:anglerfish', 
      'tide:bedrock_tetra', 
      'tide:cave_crawler', 
      'tide:cave_eel', 
      'tide:chasm_eel', 
      'tide:crystalline_carp', 
      'tide:crystal_shrimp', 
      'tide:deep_grouper', 
      'tide:devils_hole_pupfish', 
      'tide:dripstone_darter', 
      'tide:echo_snapper', 
      'tide:gilded_minnow', 
      'tide:glowfish', 
      'tide:iron_tetra', 
      'tide:lapis_lanternfish', 
      'tide:luminescent_jellyfish', 
      'tide:midas_fish', 
      'tide:shadow_snapper', 
      'tide:windbass'
    ],
    [
      Text.translate('collectionTooltips.aquarium'), 
      Text.translate('collectionTooltips.undergroundCompletion')
    ])
  event.add(
    [
      'tide:alpha_fish', 
      'tide:bedrock_bug', 
      'tide:blue_neonfish', 
      'tide:darkness_eater', 
      'tide:deep_blue', 
      'tide:incandescent_larva', 
      'tide:judgment_fish', 
      'tide:nephrosilu', 
      'tide:pentapus', 
      'tide:shadow_shark', 
      'tide:sleepy_carp', 
      'tide:vengeance'
    ],
    [
      Text.translate('collectionTooltips.aquarium'), 
      Text.translate('collectionTooltips.voidCompletion')
    ])
  event.add(
    [
      'tide:ash_perch', 
      'tide:ember_koi', 
      'tide:inferno_guppy', 
      'tide:magma_mackerel', 
      'tide:obsidian_pike', 
      'tide:volcano_tuna'
    ],
    [
      Text.translate('collectionTooltips.aquarium'), 
      Text.translate('collectionTooltips.specialCompletion')
    ])
  event.add(
    [
      'minecraft:bamboo', 
      'minecraft:beetroot_seeds', 
      'minecraft:brown_mushroom', 
      'minecraft:cactus', 
      'minecraft:carrot', 
      'minecraft:cocoa_beans', 
      'minecraft:glow_berries', 
      'minecraft:kelp', 
      'minecraft:potato', 
      'minecraft:red_mushroom', 
      'minecraft:sugar_cane', 
      'minecraft:sweet_berries', 
      'minecraft:wheat_seeds', 
      'minecraft:melon_slice', 
      'minecraft:pumpkin', 
      'minecraft:apple'
    ],
    [
      Text.translate('collectionTooltips.floraCompendium'), 
      Text.translate('collectionTooltips.vanillaFoodsCompletion')
    ])
  event.add(
    [
      'farm_and_charm:corn', 
      'farm_and_charm:oat', 
      'farm_and_charm:barley', 
      'farm_and_charm:lettuce', 
      'farm_and_charm:onion', 
      'farm_and_charm:tomato', 
      'farm_and_charm:strawberry', 
      'farm_and_charm:wild_nettle', 
      'farm_and_charm:wild_ribwort', 
      'herbalbrews:yerba_mate_leaf', 
      'herbalbrews:rooibos_leaf', 
      'herbalbrews:coffee_beans', 
      'vinery:red_grape', 
      'vinery:white_grape', 
      'vinery:savanna_grapes_red', 
      'vinery:savanna_grapes_white', 
      'vinery:taiga_grapes_red', 
      'vinery:taiga_grapes_white', 
      'vinery:jungle_grapes_red', 
      'vinery:jungle_grapes_white', 
      'vinery:cherry', 
      'biomeswevegone:blueberries', 
      'biomeswevegone:green_apple', 
      'yungscavebiomes:prickly_peach', 
      'biomeswevegone:aloe_vera', 
      'biomeswevegone:horseweed', 
      'biomeswevegone:oddion_bulb', 
      'biomeswevegone:pale_pumpkin', 
      'wildernature:hazelnut', 
      'beachparty:coconut'
    ],
    [
      Text.translate('collectionTooltips.floraCompendium'), 
      Text.translate('collectionTooltips.moddedFoodsCompletion')
    ])
  event.add(
    [
      'minecraft:allium', 
      'minecraft:azure_bluet', 
      'minecraft:blue_orchid', 
      'minecraft:cornflower', 
      'minecraft:dandelion', 
      'minecraft:lilac', 
      'minecraft:lily_of_the_valley', 
      'minecraft:orange_tulip', 
      'minecraft:oxeye_daisy', 
      'minecraft:peony', 
      'minecraft:pink_tulip', 
      'minecraft:poppy', 
      'minecraft:red_tulip', 
      'minecraft:rose_bush', 
      'minecraft:sunflower', 
      'minecraft:white_tulip', 
      'minecraft:wither_rose', 
      'minecraft:torchflower_seeds'
    ],
    [
      Text.translate('collectionTooltips.floraCompendium'), 
      Text.translate('collectionTooltips.vanillaFlowerCompletion')
    ])
  event.add(
    [
      'minecraft:acacia_sapling', 
      'minecraft:azalea', 
      'minecraft:birch_sapling', 
      'minecraft:cherry_sapling', 
      'minecraft:dark_oak_sapling', 
      'minecraft:jungle_sapling', 
      'minecraft:oak_sapling', 
      'minecraft:spruce_sapling', 
      'minecraft:mangrove_propagule'
    ],
    [
      Text.translate('collectionTooltips.floraCompendium'), 
      Text.translate('collectionTooltips.vanillaSaplingCompletion')
    ])
  event.add(
    [
      'minecraft:flowering_azalea', 
      'minecraft:moss_block', 
      'minecraft:moss_carpet', 
      'minecraft:pink_petals', 
      'minecraft:spore_blossom', 
      'minecraft:big_dripleaf', 
      'minecraft:sea_pickle', 
      'minecraft:lily_pad', 
      'minecraft:vine', 
      'minecraft:glow_lichen'
    ],
    [
      Text.translate('collectionTooltips.floraCompendium'), 
      Text.translate('collectionTooltips.vanillaFloraCompletion')
    ])
  event.add(
    [
      'biomeswevegone:araucaria_sapling', 
      'biomeswevegone:aspen_sapling', 
      'biomeswevegone:baobab_sapling', 
      'biomeswevegone:blue_enchanted_sapling', 
      'biomeswevegone:blue_spruce_sapling', 
      'biomeswevegone:brown_birch_sapling', 
      'biomeswevegone:brown_oak_sapling', 
      'biomeswevegone:cika_sapling', 
      'biomeswevegone:cypress_sapling', 
      'biomeswevegone:ebony_sapling', 
      'biomeswevegone:holly_sapling', 
      'biomeswevegone:ironwood_sapling', 
      'biomeswevegone:jacaranda_sapling', 
      'biomeswevegone:maple_sapling', 
      'biomeswevegone:orange_birch_sapling', 
      'biomeswevegone:orange_spruce_sapling', 
      'biomeswevegone:orchard_sapling', 
      'biomeswevegone:palo_verde_sapling', 
      'biomeswevegone:pine_sapling', 
      'meadow:pine_sapling', 
      'biomeswevegone:red_maple_sapling', 
      'biomeswevegone:red_oak_sapling', 
      'biomeswevegone:red_spruce_sapling', 
      'biomeswevegone:redwood_sapling', 
      'biomeswevegone:silver_maple_sapling', 
      'biomeswevegone:skyris_sapling', 
      'biomeswevegone:spirit_sapling', 
      'biomeswevegone:white_mangrove_sapling', 
      'biomeswevegone:white_sakura_sapling', 
      'biomeswevegone:witch_hazel_sapling', 
      'biomeswevegone:yellow_birch_sapling', 
      'biomeswevegone:yellow_sakura_sapling', 
      'biomeswevegone:yucca_sapling', 
      'biomeswevegone:zelkova_sapling', 
      'vinery:dark_cherry_sapling', 
      'beachparty:palm_sprout'
    ],
    [
      Text.translate('collectionTooltips.floraCompendium'), 
      Text.translate('collectionTooltips.moddedSaplings')
    ])
  event.add(
    [
      'biomeswevegone:jacaranda_bush', 
      'biomeswevegone:blue_rose_bush', 
      'biomeswevegone:hydrangea_bush', 
      'biomeswevegone:firecracker_flower_bush'
    ],
    [
      Text.translate('collectionTooltips.floraCompendium'), 
      Text.translate('collectionTooltips.biomeBushes')
    ])
  event.add(
    [
      'biomeswevegone:clover_patch', 
      'biomeswevegone:flower_patch', 
      'biomeswevegone:leaf_pile', 
      'biomeswevegone:water_silk', 
      'biomeswevegone:white_sakura_petals', 
      'biomeswevegone:yellow_sakura_petals'
    ],
    [
      Text.translate('collectionTooltips.floraCompendium'), 
      Text.translate('collectionTooltips.biomeGroundCovers')
    ])
  event.add(
    [
      'biomeswevegone:alpine_bellflower', 
      'biomeswevegone:amaranth', 
      'biomeswevegone:angelica', 
      'biomeswevegone:bistort', 
      'biomeswevegone:black_rose', 
      'biomeswevegone:california_poppy', 
      'biomeswevegone:crocus', 
      'biomeswevegone:cyan_amaranth', 
      'biomeswevegone:cyan_rose', 
      'biomeswevegone:delphinium', 
      'biomeswevegone:fairy_slipper', 
      'biomeswevegone:foxglove', 
      'biomeswevegone:iris', 
      'biomeswevegone:japanese_orchid', 
      'biomeswevegone:kovan_flower', 
      'biomeswevegone:lazarus_bellflower', 
      'biomeswevegone:lollipop_flower', 
      'biomeswevegone:magenta_amaranth', 
      'biomeswevegone:orange_amaranth', 
      'biomeswevegone:orange_daisy', 
      'biomeswevegone:peach_leather_flower', 
      'biomeswevegone:pink_anemone', 
      'biomeswevegone:pink_daffodil', 
      'biomeswevegone:protea_flower', 
      'biomeswevegone:purple_amaranth', 
      'biomeswevegone:rose', 
      'biomeswevegone:snowdrops', 
      'biomeswevegone:winter_cyclamen', 
      'biomeswevegone:winter_rose', 
      'biomeswevegone:winter_scilla', 
      'biomeswevegone:winter_succulent', 
      'biomeswevegone:yellow_daffodil', 
      'meadow:alpine_poppy', 
      'meadow:delphinium', 
      'meadow:saxifrage', 
      'meadow:enzian', 
      'meadow:fire_lily', 
      'meadow:eriophorum', 
      'meadow:eriophorum_tall', 
      'candlelight:rose'
    ],
    [
      Text.translate('collectionTooltips.floraCompendium'), 
      Text.translate('collectionTooltips.biomeFlowers')
    ])
  event.add(
    [
      'biomeswevegone:pink_allium', 
      'biomeswevegone:white_allium', 
      'biomeswevegone:tall_allium', 
      'biomeswevegone:tall_pink_allium', 
      'biomeswevegone:tall_white_allium', 
      'biomeswevegone:allium_flower_bush', 
      'biomeswevegone:pink_allium_flower_bush', 
      'biomeswevegone:white_allium_flower_bush', 
      'biomeswevegone:cyan_tulip', 
      'biomeswevegone:green_tulip', 
      'biomeswevegone:magenta_tulip', 
      'biomeswevegone:purple_tulip', 
      'biomeswevegone:yellow_tulip'
    ],
    [
      Text.translate('collectionTooltips.floraCompendium'), 
      Text.translate('collectionTooltips.biomeAlliumAndTulips')
    ])
  event.add(
    [
      'biomeswevegone:beach_grass', 
      'biomeswevegone:cattail_sprout', 
      'biomeswevegone:fluorescent_cattail_sprout', 
      'biomeswevegone:green_mushroom', 
      'biomeswevegone:prairie_grass', 
      'biomeswevegone:shrub', 
      'biomeswevegone:white_puffball_spores', 
      'meadow:small_fir', 
      'yungscavebiomes:prickly_peach_cactus', 
      'yungscavebiomes:prickly_vines', 
      'yungscavebiomes:frost_lily', 
      'biomeswevegone:green_mushroom', 
      'biomeswevegone:shelf_fungi', 
      'biomeswevegone:weeping_milkcap', 
      'biomeswevegone:wood_blewit'
    ],
    [
      Text.translate('collectionTooltips.floraCompendium'), 
      Text.translate('collectionTooltips.biomeMisc')
    ])
  event.add(
    [
      'minecraft:cobblestone', 
      'minecraft:mossy_cobblestone', 
      'minecraft:cobbled_deepslate', 
      'minecraft:diorite', 
      'minecraft:granite', 
      'minecraft:andesite', 
      'minecraft:sandstone', 
      'minecraft:red_sandstone', 
      'minecraft:calcite', 
      'minecraft:dripstone_block', 
      'minecraft:pointed_dripstone', 
      'minecraft:smooth_basalt', 
      'minecraft:tuff', 
      'minecraft:obsidian'
    ],
    [
      Text.translate('collectionTooltips.mineralMuseum'), 
      Text.translate('collectionTooltips.vanillaBlocksCompletion')
    ])
  event.add(
    [
      'minecraft:raw_copper', 
      'minecraft:raw_iron', 
      'create:raw_zinc', 
      'minecraft:raw_gold', 
      'minecraft:coal', 
      'minecraft:redstone'
    ],
    [
      Text.translate('collectionTooltips.mineralMuseum'), 
      Text.translate('collectionTooltips.oreCompletion')
    ])
  event.add(
    [
      'minecraft:lapis_lazuli', 
      'minecraft:amethyst_shard', 
      'minecraft:diamond', 
      'irons_jewelry:ruby', 
      'irons_jewelry:sapphire', 
      'irons_jewelry:topaz', 
      'irons_jewelry:moonstone', 
      'irons_jewelry:peridot', 
      'irons_jewelry:onyx', 
      'irons_jewelry:garnet'
    ],
    [
      Text.translate('collectionTooltips.mineralMuseum'), 
      Text.translate('collectionTooltips.gemsCompletion')
    ])
  event.add(
    [
      'biomeswevegone:blue_sandstone', 
      'biomeswevegone:borealis_ice', 
      'biomeswevegone:cracked_red_sand', 
      'biomeswevegone:dacite', 
      'biomeswevegone:florus_stem', 
      'biomeswevegone:lush_grass_block', 
      'biomeswevegone:mossy_stone', 
      'biomeswevegone:overgrown_stone', 
      'biomeswevegone:pale_mud', 
      'biomeswevegone:red_rock', 
      'biomeswevegone:rocky_stone', 
      'biomeswevegone:white_dacite', 
      'biomeswevegone:windswept_sand', 
      'biomeswevegone:windswept_sandstone', 
      'meadow:limestone', 
      'yungscavebiomes:icicle', 
      'yungscavebiomes:rare_ice', 
      'yungscavebiomes:ancient_sand', 
      'yungscavebiomes:ancient_sandstone'
    ],
    [
      Text.translate('collectionTooltips.mineralMuseum'), 
      Text.translate('collectionTooltips.moddedCompletion')
    ])
  event.add(
    [
      'create:crimsite', 
      'create:asurine', 
      'create:limestone', 
      'create:ochrum', 
      'create:scoria', 
      'create:scorchia', 
      'create:veridium'
    ],
    [
      Text.translate('collectionTooltips.mineralMuseum'), 
      Text.translate('collectionTooltips.createCompletion')
    ])
  event.add(
    [
      'bakery:apple_jam', 
      'bakery:chocolate_jam', 
      'bakery:glowberry_jam', 
      'bakery:strawberry_jam', 
      'bakery:sweetberry_jam', 
      'bakery:chocolate_truffle', 
      'bakery:pudding', 
      'candlelight:chicken_teriyaki', 
      'candlelight:chocolate_mousse', 
      'candlelight:khinkali', 
      'candlelight:mushroom_soup', 
      'candlelight:pasta_with_mozzarella', 
      'candlelight:salmon_on_white_wine', 
      'candlelight:tomato_soup', 
      'farm_and_charm:barley_soup', 
      'farm_and_charm:corn_grits', 
      'farm_and_charm:goulash', 
      'farm_and_charm:nettle_tea', 
      'farm_and_charm:onion_soup', 
      'farm_and_charm:potato_soup', 
      'farm_and_charm:ribwort_tea', 
      'farm_and_charm:simple_tomato_soup', 
      'farm_and_charm:strawberry_tea', 
      'brewery:dumplings', 
      'brewery:sausage'
    ],
    [
      Text.translate('collectionTooltips.cookingCollection'), 
      Text.translate('collectionTooltips.cookingPotCompletion')
    ])
  event.add(
    [
      'brewery:half_chicken', 
      'brewery:mashed_potatoes', 
      'farm_and_charm:lamb_ham'
    ],
    [
      Text.translate('collectionTooltips.cookingCollection'), 
      Text.translate('collectionTooltips.mincerCompletion')
    ])
  event.add(
    [
      'brewery:potato_salad', 
      'candlelight:beef_tartare', 
      'candlelight:beetroot_salad', 
      'candlelight:fresh_garden_salad', 
      'candlelight:harvest_plate', 
      'candlelight:mozzarella', 
      'candlelight:salad', 
      'candlelight:tomato_mozzarella_salad', 
      'farm_and_charm:farmer_salad', 
      'farm_and_charm:oatmeal_with_strawberries'
    ],
    [
      Text.translate('collectionTooltips.cookingCollection'), 
      Text.translate('collectionTooltips.craftingBowlCompletion')
    ])
  event.add(
    [
      'bakery:apple_pie', 
      'bakery:baguette', 
      'bakery:braided_bread', 
      'bakery:bread', 
      'bakery:bun', 
      'bakery:bundt_cake', 
      'bakery:chocolate_tart', 
      'bakery:cornet', 
      'bakery:croissant', 
      'bakery:crusty_bread', 
      'bakery:glowberry_tart', 
      'bakery:grilled_bacon_sandwich', 
      'bakery:grilled_salmon_sandwich', 
      'bakery:jam_roll', 
      'bakery:linzer_tart', 
      'bakery:misslilitu_biscuit', 
      'bakery:toast', 
      'bakery:waffle', 
      'brewery:gingerbread', 
      'brewery:pork_knuckle', 
      'brewery:pretzel', 
      'candlelight:beef_wellington', 
      'candlelight:chicken_alfredo', 
      'candlelight:chicken_with_vegetables', 
      'candlelight:lasagne', 
      'candlelight:pork_ribs', 
      'candlelight:roastbeef_with_glazed_carrots', 
      'candlelight:tropical_fish_supreme', 
      'farm_and_charm:baked_lamb_ham', 
      'farm_and_charm:farmers_bread', 
      'farm_and_charm:grandmothers_strawberry_cake', 
      'farm_and_charm:pasta_with_onion_sauce', 
      'farm_and_charm:potato_with_roast_meat', 
      'farm_and_charm:roasted_chicken', 
      'farm_and_charm:roasted_corn', 
      'farm_and_charm:stuffed_chicken', 
      'farm_and_charm:stuffed_rabbit'
    ],
    [
      Text.translate('collectionTooltips.cookingCollection'), 
      Text.translate('collectionTooltips.stoveCompletion')
    ])
  event.add(
    [
      'bakery:sweetberry_glazed_cookie', 
      'bakery:strawberry_glazed_cookie', 
      'bakery:chocolate_glazed_cookie', 
      'bakery:sweetberry_cupcake', 
      'bakery:strawberry_cupcake', 
      'bakery:apple_cupcake', 
      'bakery:sweetberry_cake', 
      'bakery:strawberry_cake', 
      'bakery:chocolate_cake', 
      'bakery:chocolate_gateau'
    ],
    [
      Text.translate('collectionTooltips.cookingCollection'), 
      Text.translate('collectionTooltips.cakingCompletion')
    ])
  event.add(
    [
      'meadow:cheese_block', 
      'meadow:sheep_cheese_block', 
      'meadow:goat_cheese_block', 
      'meadow:buffalo_cheese_block', 
      'meadow:grain_cheese_block'
    ],
    [
      Text.translate('collectionTooltips.cookingCollection'), 
      Text.translate('collectionTooltips.cheeseFormCompletion')
    ])
  event.add(
    [
      'meadow:cooked_buffalo_meat', 
      'meadow:sausage_with_cheese', 
      'meadow:roasted_ham'
    ],
    [
      Text.translate('collectionTooltips.cookingCollection'), 
      Text.translate('collectionTooltips.cookingCaldronCompletion')
    ])
  event.add(
    [
      'brewery:fried_chicken', 
      'candlelight:beef_with_mushroom_in_wine_and_potatoes', 
      'candlelight:bolognese', 
      'candlelight:fillet_steak', 
      'candlelight:omelet', 
      'candlelight:pasta_with_lettuce', 
      'candlelight:pasta_with_bolognese', 
      'candlelight:roasted_lamb_with_lettuce', 
      'farm_and_charm:bacon_with_eggs', 
      'farm_and_charm:barley_patties_with_potatoes', 
      'farm_and_charm:beef_patty_with_vegetables', 
      'farm_and_charm:chicken_wrapped_in_bacon', 
      'farm_and_charm:cooked_cod', 
      'farm_and_charm:cooked_salmon', 
      'farm_and_charm:lamb_with_corn', 
      'farm_and_charm:oat_pancake', 
      'farm_and_charm:sausage_with_oat_patty'
    ],
    [
      Text.translate('collectionTooltips.cookingCollection'), 
      Text.translate('collectionTooltips.roasterCompletion')
    ])
  event.add(
    [
      'beachparty:cocoa_cocktail', 
      'beachparty:coconut_cocktail', 
      'beachparty:honey_cocktail', 
      'beachparty:melon_cocktail', 
      'beachparty:pumpkin_cocktail', 
      'beachparty:sweetberries_cocktail'
    ],
    [
      Text.translate('collectionTooltips.cookingCollection'), 
      Text.translate('collectionTooltips.palmBarCompletion')
    ])
  event.add(
    [
      'herbalbrews:green_tea', 
      'herbalbrews:black_tea', 
      'herbalbrews:oolong_tea', 
      'herbalbrews:hibiscus_tea', 
      'herbalbrews:lavender_tea', 
      'herbalbrews:rooibos_tea', 
      'herbalbrews:coffee', 
      'herbalbrews:milk_coffee', 
      'herbalbrews:yerba_mate_tea'
    ],
    [
      Text.translate('collectionTooltips.cookingCollection'), 
      Text.translate('collectionTooltips.teaBrewingCompletion')
    ])
  event.add(
    [
      'vinery:red_grapejuice', 
      'vinery:white_grapejuice', 
      'vinery:red_taiga_grapejuice', 
      'vinery:white_taiga_grapejuice', 
      'vinery:red_jungle_grapejuice', 
      'vinery:white_jungle_grapejuice', 
      'vinery:red_savanna_grapejuice', 
      'vinery:white_savanna_grapejuice', 
      'vinery:apple_juice'
    ],
    [
      Text.translate('collectionTooltips.cookingCollection'), 
      Text.translate('collectionTooltips.juicingCompletion')
    ])
  event.add(
    [
      'vinery:aegis_wine', 
      'vinery:apple_cider', 
      'vinery:apple_wine', 
      'vinery:bolvar_wine', 
      'vinery:bottle_mojang_noir', 
      'vinery:chenet_wine', 
      'vinery:cherry_wine', 
      'vinery:chorus_wine', 
      'vinery:clark_wine', 
      'vinery:creepers_crush', 
      'vinery:cristel_wine', 
      'vinery:eiswein', 
      'vinery:glowing_wine', 
      'vinery:jellie_wine', 
      'vinery:jo_special_mixture', 
      'vinery:kelp_cider', 
      'vinery:lilitu_wine', 
      'vinery:magnetic_wine', 
      'vinery:mead', 
      'vinery:mellohi_wine', 
      'vinery:noir_wine', 
      'vinery:red_wine', 
      'vinery:solaris_wine', 
      'vinery:stal_wine', 
      'vinery:strad_wine', 
      'vinery:villagers_fright'
    ],
    [
      Text.translate('collectionTooltips.cookingCollection'), 
      Text.translate('collectionTooltips.barrelBrewingCompletion')
    ])
  event.add(
    [
      'brewery:beer_barley', 
      'brewery:beer_haley', 
      'brewery:beer_hops', 
      'brewery:beer_nettle', 
      'brewery:beer_oat', 
      'brewery:beer_wheat'
    ],
    [
      Text.translate('collectionTooltips.cookingCollection'), 
      Text.translate('collectionTooltips.beerBrewingCompletion')
    ])
  event.add(
    [
      'brewery:whiskey_ak', 
      'brewery:whiskey_cristelwalker', 
      'brewery:whiskey_carrasconlabel', 
      'brewery:whiskey_highland_hearth', 
      'brewery:whiskey_jojannik', 
      'brewery:whiskey_lilitusinglemalt', 
      'brewery:whiskey_maggoallan'
    ],
    [
      Text.translate('collectionTooltips.cookingCollection'), 
      Text.translate('collectionTooltips.copperBrewingCompletion')
    ])
  event.add(
    [
      'brewery:dark_brew', 
      'brewery:whiskey_jamesons_malt', 
      'brewery:whiskey_smokey_reverie'
    ],
    [
      Text.translate('collectionTooltips.cookingCollection'), 
      Text.translate('collectionTooltips.netheriteBrewingCompletion')
    ])

})