ItemEvents.modifyTooltips(event => {
  event.add(
    [
      'minecraft:cod', 
      'minecraft:tropical_fish', 
      'minecraft:salmon', 
      'minecraft:pufferfish'
    ],
    [
      Text.translate('collectionTooltips.aquarium'), 
      Text.translate('collectionTooltips.vanillaCompletion')
    ])
  event.add(
    [
      'tide:bass', 
      'tide:bluegill', 
      'tide:catfish', 
      'tide:clayfish', 
      'tide:guppy', 
      'tide:mint_carp', 
      'tide:pike', 
      'tide:yellow_perch'
    ],
    [
      Text.translate('collectionTooltips.aquarium'), 
      Text.translate('collectionTooltips.freshwaterCompletion')
    ])
  event.add(
    [
      'tide:angelfish', 
      'tide:barracuda', 
      'tide:mackerel', 
      'tide:ocean_perch', 
      'tide:sailfish', 
      'tide:trout', 
      'tide:tuna'
    ],
    [
      Text.translate('collectionTooltips.aquarium'), 
      Text.translate('collectionTooltips.saltwaterCompletion')
    ])
  event.add(
    [
      'tide:deep_grouper', 
      'tide:shadow_snapper', 
      'tide:luminescent_jellyfish', 
      'tide:abyss_angler', 
      'tide:lapis_lanternfish', 
      'tide:crystalline_carp', 
      'tide:bedrock_tetra', 
      'tide:ember_koi', 
      'tide:inferno_guppy', 
      'tide:obsidian_pike', 
      'tide:volcano_tuna', 
      'tide:cave_eel', 
      'tide:cave_crawler', 
      'tide:glowfish', 
      'tide:anglerfish', 
      'tide:iron_tetra', 
      'tide:crystal_shrimp', 
      'tide:gilded_minnow'
    ],
    [
      Text.translate('collectionTooltips.aquarium'), 
      Text.translate('collectionTooltips.alternativeLocalesCompletion')
    ])
  event.add(
    [
      'tide:blossom_bass', 
      'tide:echofin_snapper', 
      'tide:dripstone_darter', 
      'tide:fluttergill', 
      'tide:sunspike_goby', 
      'tide:birch_trout', 
      'tide:mirage_catfish', 
      'tide:slimefin_snapper', 
      'tide:sporestalker', 
      'tide:leafback', 
      'tide:pine_perch', 
      'tide:sandskipper', 
      'tide:stonefish', 
      'tide:frostbite_flounder', 
      'tide:oakfish', 
      'tide:prarie_pike'
    ],
    [
      Text.translate('collectionTooltips.aquarium'), 
      Text.translate('collectionTooltips.specialCompletion')
    ])
  event.add(
    [
      'minecraft:bamboo', 
      'minecraft:beetroot_seeds', 
      'minecraft:brown_mushroom', 
      'minecraft:cactus', 
      'minecraft:carrot', 
      'minecraft:cocoa_beans', 
      'minecraft:glow_berries', 
      'minecraft:kelp', 
      'minecraft:potato', 
      'minecraft:red_mushroom', 
      'minecraft:sugar_cane', 
      'minecraft:sweet_berries', 
      'minecraft:wheat_seeds'
    ],
    [
      Text.translate('collectionTooltips.floraCompendium'), 
      Text.translate('collectionTooltips.vanillaFoodsCompletion')
    ])
  event.add(
    [
      'minecraft:allium', 
      'minecraft:azure_bluet', 
      'minecraft:blue_orchid', 
      'minecraft:cornflower', 
      'minecraft:dandelion', 
      'minecraft:lilac', 
      'minecraft:lily_of_the_valley', 
      'minecraft:orange_tulip', 
      'minecraft:oxeye_daisy', 
      'minecraft:peony', 
      'minecraft:pink_tulip', 
      'minecraft:poppy', 
      'minecraft:red_tulip', 
      'minecraft:rose_bush', 
      'minecraft:sunflower', 
      'minecraft:white_tulip', 
      'minecraft:wither_rose', 
      'minecraft:torchflower_seeds'
    ],
    [
      Text.translate('collectionTooltips.floraCompendium'), 
      Text.translate('collectionTooltips.vanillaFlowerCompletion')
    ])
  event.add(
    [
      'minecraft:acacia_sapling', 
      'minecraft:azalea', 
      'minecraft:birch_sapling', 
      'minecraft:cherry_sapling', 
      'minecraft:dark_oak_sapling', 
      'minecraft:jungle_sapling', 
      'minecraft:oak_sapling', 
      'minecraft:spruce_sapling', 
      'minecraft:mangrove_propagule'
    ],
    [
      Text.translate('collectionTooltips.floraCompendium'), 
      Text.translate('collectionTooltips.vanillaSaplingCompletion')
    ])
  event.add(
    [
      'minecraft:flowering_azalea', 
      'minecraft:moss_block', 
      'minecraft:moss_carpet', 
      'minecraft:pink_petals', 
      'minecraft:spore_blossom', 
      'minecraft:big_dripleaf', 
      'minecraft:sea_pickle', 
      'minecraft:lily_pad'
    ],
    [
      Text.translate('collectionTooltips.floraCompendium'), 
      Text.translate('collectionTooltips.vanillaFloraCompletion')
    ])
  event.add(
    [
      'biomeswevegone:aloe_vera', 
      'biomeswevegone:horseweed', 
      'biomeswevegone:oddion_bulb', 
      'biomeswevegone:pale_pumpkin'
    ],
    [
      Text.translate('collectionTooltips.floraCompendium'), 
      Text.translate('collectionTooltips.biomeFoods')
    ])
  event.add(
    [
      'biomeswevegone:araucaria_sapling', 
      'biomeswevegone:aspen_sapling', 
      'biomeswevegone:baobab_sapling', 
      'biomeswevegone:blue_enchanted_sapling', 
      'biomeswevegone:blue_spruce_sapling', 
      'biomeswevegone:brown_birch_sapling', 
      'biomeswevegone:brown_oak_sapling', 
      'biomeswevegone:cika_sapling', 
      'biomeswevegone:cypress_sapling', 
      'biomeswevegone:ebony_sapling', 
      'biomeswevegone:holly_sapling', 
      'biomeswevegone:ironwood_sapling', 
      'biomeswevegone:jacaranda_sapling', 
      'biomeswevegone:maple_sapling', 
      'biomeswevegone:orange_birch_sapling', 
      'biomeswevegone:orange_spruce_sapling', 
      'biomeswevegone:orchard_sapling', 
      'biomeswevegone:palo_verde_sapling', 
      'biomeswevegone:pine_sapling', 
      'biomeswevegone:red_maple_sapling', 
      'biomeswevegone:red_oak_sapling', 
      'biomeswevegone:red_spruce_sapling', 
      'biomeswevegone:redwood_sapling', 
      'biomeswevegone:silver_maple_sapling', 
      'biomeswevegone:skyris_sapling', 
      'biomeswevegone:spirit_sapling', 
      'biomeswevegone:white_mangrove_sapling', 
      'biomeswevegone:white_sakura_sapling', 
      'biomeswevegone:witch_hazel_sapling', 
      'biomeswevegone:yellow_birch_sapling', 
      'biomeswevegone:yellow_sakura_sapling', 
      'biomeswevegone:yucca_sapling', 
      'biomeswevegone:zelkova_sapling'
    ],
    [
      Text.translate('collectionTooltips.floraCompendium'), 
      Text.translate('collectionTooltips.biomeSaplings')
    ])
  event.add(
    [
      'biomeswevegone:jacaranda_bush', 
      'biomeswevegone:blue_rose_bush', 
      'biomeswevegone:hydrangea_bush', 
      'biomeswevegone:firecracker_flower_bush'
    ],
    [
      Text.translate('collectionTooltips.floraCompendium'), 
      Text.translate('collectionTooltips.biomeBushes')
    ])
  event.add(
    [
      'biomeswevegone:clover_patch', 
      'biomeswevegone:flower_patch', 
      'biomeswevegone:leaf_pile', 
      'biomeswevegone:water_silk', 
      'biomeswevegone:white_sakura_petals', 
      'biomeswevegone:yellow_sakura_petals'
    ],
    [
      Text.translate('collectionTooltips.floraCompendium'), 
      Text.translate('collectionTooltips.biomeGroundCovers')
    ])
  event.add(
    [
      'biomeswevegone:alpine_bellflower', 
      'biomeswevegone:amaranth', 
      'biomeswevegone:angelica', 
      'biomeswevegone:bistort', 
      'biomeswevegone:black_rose', 
      'biomeswevegone:california_poppy', 
      'biomeswevegone:crocus', 
      'biomeswevegone:cyan_amaranth', 
      'biomeswevegone:cyan_rose', 
      'biomeswevegone:delphinium', 
      'biomeswevegone:fairy_slipper', 
      'biomeswevegone:foxglove', 
      'biomeswevegone:iris', 
      'biomeswevegone:japanese_orchid', 
      'biomeswevegone:kovan_flower', 
      'biomeswevegone:lazarus_bellflower', 
      'biomeswevegone:lollipop_flower', 
      'biomeswevegone:magenta_amaranth', 
      'biomeswevegone:orange_amaranth', 
      'biomeswevegone:orange_daisy', 
      'biomeswevegone:peach_leather_flower', 
      'biomeswevegone:pink_anemone', 
      'biomeswevegone:pink_daffodil', 
      'biomeswevegone:protea_flower', 
      'biomeswevegone:purple_amaranth', 
      'biomeswevegone:rose', 
      'biomeswevegone:snowdrops', 
      'biomeswevegone:winter_cyclamen', 
      'biomeswevegone:winter_rose', 
      'biomeswevegone:winter_scilla', 
      'biomeswevegone:winter_succulent', 
      'biomeswevegone:yellow_daffodil'
    ],
    [
      Text.translate('collectionTooltips.floraCompendium'), 
      Text.translate('collectionTooltips.biomeFlowers')
    ])
  event.add(
    [
      'biomeswevegone:pink_allium', 
      'biomeswevegone:white_allium', 
      'biomeswevegone:tall_allium', 
      'biomeswevegone:tall_pink_allium', 
      'biomeswevegone:tall_white_allium', 
      'biomeswevegone:allium_flower_bush', 
      'biomeswevegone:pink_allium_flower_bush', 
      'biomeswevegone:white_allium_flower_bush', 
      'biomeswevegone:cyan_tulip', 
      'biomeswevegone:green_tulip', 
      'biomeswevegone:magenta_tulip', 
      'biomeswevegone:purple_tulip', 
      'biomeswevegone:yellow_tulip'
    ],
    [
      Text.translate('collectionTooltips.floraCompendium'), 
      Text.translate('collectionTooltips.biomeAlliumAndTulips')
    ])
  event.add(
    [
      'biomeswevegone:beach_grass', 
      'biomeswevegone:cattail_sprout', 
      'biomeswevegone:fluorescent_cattail_sprout', 
      'biomeswevegone:green_mushroom', 
      'biomeswevegone:prairie_grass', 
      'biomeswevegone:shrub', 
      'biomeswevegone:white_puffball_spores'
    ],
    [
      Text.translate('collectionTooltips.floraCompendium'), 
      Text.translate('collectionTooltips.biomeMisc')
    ])

})