const SellingFoodList = {
  foodWithDifferentOutputs = {
    'meadow:cheesecake': 'meadow:cheesecake_slice',
    'meadow:cheese_tart': 'meadow:cheese_tart_slice',
    'bakery:strawberry_cake': 'bakery:strawberry_cake_slice',
    'bakery:sweetberry_cake': 'bakery:sweetberry_cake_slice',
    'bakery:chocolate_cake': 'bakery:chocolate_cake_slice',
    'bakery:chocolate_gateau': 'bakery:chocolate_gateau_slice',
    'bakery:bundt_cake': 'bakery:bundt_cake_slice',
    'bakery:linzer_tart': 'bakery:linzer_tart_slice',
    'bakery:apple_pie': 'bakery:apple_pie_slice',
    'bakery:glowberry_pie': 'bakery:glowberry_pie_slice',
    'bakery:chocolate_tart': 'bakery:chocolate_tart_slice',
    'bakery:pudding': 'bakery:pudding_slice',
    'meadow:amethyst_cheese_block': 'meadow:piece_of_amethyst_cheese',
    'meadow:buffalo_cheese_block': 'meadow:piece_of_buffalo_cheese',
    'meadow:cheese_block': 'meadow:piece_of_cheese',
    'meadow:goat_cheese_block': 'meadow:piece_of_goat_cheese',
    'meadow:grain_cheese_block': 'meadow:piece_of_grain_cheese',
    'meadow:sheep_cheese_block': 'meadow:piece_of_sheep_cheese',
    'meadow:warped_cheese_block': 'meadow:piece_of_warped_cheese'
  },
  foods = [
    "bakery:apple_jam",
    "bakery:chocolate_jam",
    "bakery:glowberry_jam",
    "bakery:strawberry_jam",
    "bakery:sweetberry_jam",
    "bakery:chocolate_truffle",
    "bakery:pudding",
    "candlelight:chicken_teriyaki",
    "candlelight:chocolate_mousse",
    "candlelight:khinkali",
    "candlelight:mushroom_soup",
    "candlelight:pasta_with_mozzarella",
    "candlelight:salmon_on_white_wine",
    "candlelight:tomato_soup",
    "farm_and_charm:barley_soup",
    "farm_and_charm:corn_grits",
    "farm_and_charm:goulash",
    "farm_and_charm:nettle_tea",
    "farm_and_charm:onion_soup",
    "farm_and_charm:potato_soup",
    "farm_and_charm:ribwort_tea",
    "farm_and_charm:simple_tomato_soup",
    "farm_and_charm:strawberry_tea",
    "brewery:dumplings",
    "brewery:sausage",
    "brewery:half_chicken",
    "brewery:mashed_potatoes",
    "farm_and_charm:lamb_ham",
    "brewery:potato_salad",
    "candlelight:beef_tartare",
    "candlelight:beetroot_salad",
    "candlelight:fresh_garden_salad",
    "candlelight:harvest_plate",
    "candlelight:mozzarella",
    "candlelight:salad",
    "candlelight:tomato_mozzarella_salad",
    "farm_and_charm:farmer_salad",
    "farm_and_charm:oatmeal_with_strawberries",
    "bakery:apple_pie",
    "bakery:baguette",
    "bakery:braided_bread",
    "bakery:bread",
    "bakery:bun",
    "bakery:bundt_cake",
    "bakery:chocolate_tart",
    "bakery:cornet",
    "bakery:croissant",
    "bakery:crusty_bread",
    "bakery:glowberry_tart",
    "bakery:grilled_bacon_sandwich",
    "bakery:grilled_salmon_sandwich",
    "bakery:jam_roll",
    "bakery:linzer_tart",
    "bakery:misslilitu_biscuit",
    "bakery:toast",
    "bakery:waffle",
    "brewery:gingerbread",
    "brewery:pork_knuckle",
    "brewery:pretzel",
    "candlelight:beef_wellington",
    "candlelight:chicken_alfredo",
    "candlelight:chicken_with_vegetables",
    "candlelight:lasagne",
    "candlelight:pork_ribs",
    "candlelight:roastbeef_with_glazed_carrots",
    "candlelight:tropical_fish_supreme",
    "farm_and_charm:baked_lamb_ham",
    "farm_and_charm:farmers_bread",
    "farm_and_charm:grandmothers_strawberry_cake",
    "farm_and_charm:pasta_with_onion_sauce",
    "farm_and_charm:potato_with_roast_meat",
    "farm_and_charm:roasted_chicken",
    "farm_and_charm:roasted_corn",
    "farm_and_charm:stuffed_chicken",
    "farm_and_charm:stuffed_rabbit",
    "bakery:sweetberry_glazed_cookie",
    "bakery:strawberry_glazed_cookie",
    "bakery:chocolate_glazed_cookie",
    "bakery:sweetberry_cupcake",
    "bakery:strawberry_cupcake",
    "bakery:apple_cupcake",
    "bakery:sweetberry_cake",
    "bakery:strawberry_cake",
    "bakery:chocolate_cake",
    "bakery:chocolate_gateau",
    "meadow:cheese_block",
    "meadow:sheep_cheese_block",
    "meadow:goat_cheese_block",
    "meadow:buffalo_cheese_block",
    "meadow:grain_cheese_block",
    "meadow:cooked_buffalo_meat",
    "meadow:sausage_with_cheese",
    "meadow:roasted_ham",
    "brewery:fried_chicken",
    "candlelight:beef_with_mushroom_in_wine_and_potatoes",
    "candlelight:bolognese",
    "candlelight:fillet_steak",
    "candlelight:omelet",
    "candlelight:pasta_with_lettuce",
    "candlelight:pasta_with_bolognese",
    "candlelight:roasted_lamb_with_lettuce",
    "farm_and_charm:bacon_with_eggs",
    "farm_and_charm:barley_patties_with_potatoes",
    "farm_and_charm:beef_patty_with_vegetables",
    "farm_and_charm:chicken_wrapped_in_bacon",
    "farm_and_charm:cooked_cod",
    "farm_and_charm:cooked_salmon",
    "farm_and_charm:lamb_with_corn",
    "farm_and_charm:oat_pancake",
    "farm_and_charm:sausage_with_oat_patty",
    "beachparty:cocoa_cocktail",
    "beachparty:coconut_cocktail",
    "beachparty:honey_cocktail",
    "beachparty:melon_cocktail",
    "beachparty:pumpkin_cocktail",
    "beachparty:sweetberries_cocktail",
    "herbalbrews:green_tea",
    "herbalbrews:black_tea",
    "herbalbrews:oolong_tea",
    "herbalbrews:hibiscus_tea",
    "herbalbrews:lavender_tea",
    "herbalbrews:rooibos_tea",
    "herbalbrews:coffee",
    "herbalbrews:milk_coffee",
    "herbalbrews:yerba_mate_tea",
    'vinery:red_grapejuice',
    'vinery:white_grapejuice',
    'vinery:red_taiga_grapejuice',
    'vinery:white_taiga_grapejuice',
    'vinery:red_jungle_grapejuice',
    'vinery:white_jungle_grapejuice',
    'vinery:red_savanna_grapejuice',
    'vinery:white_savanna_grapejuice',
    'vinery:apple_juice',
    "vinery:aegis_wine",
    "vinery:apple_cider",
    "vinery:apple_wine",
    "vinery:bolvar_wine",
    "vinery:bottle_mojang_noir",
    "vinery:chenet_wine",
    "vinery:cherry_wine",
    "vinery:chorus_wine",
    "vinery:clark_wine",
    "vinery:creepers_crush",
    "vinery:cristel_wine",
    "vinery:eiswein",
    "vinery:glowing_wine",
    "vinery:jellie_wine",
    "vinery:jo_special_mixture",
    "vinery:kelp_cider",
    "vinery:lilitu_wine",
    "vinery:magnetic_wine",
    "vinery:mead",
    "vinery:mellohi_wine",
    "vinery:noir_wine",
    "vinery:red_wine",
    "vinery:solaris_wine",
    "vinery:stal_wine",
    "vinery:strad_wine",
    "vinery:villagers_fright",
    "brewery:beer_barley",
    "brewery:dark_brew",
    "brewery:beer_haley",
    "brewery:beer_hops",
    "brewery:beer_nettle",
    "brewery:beer_oat",
    "brewery:beer_wheat",
    "brewery:whiskey_ak",
    "brewery:whiskey_cristelwalker",
    "brewery:whiskey_carrasconlabel",
    "brewery:whiskey_highland_hearth",
    "brewery:whiskey_jamesons_malt",
    "brewery:whiskey_jojannik",
    "brewery:whiskey_lilitusinglemalt",
    "brewery:whiskey_maggoallan",
    "brewery:whiskey_smokey_reverie",
  ]
}