// priority: 2
const ParlanItems = {
  simpleCollections: {
    coats: [
      'moa_bath:bata_amarilla',
      'moa_bath:bata_azul',
      'moa_bath:bata_azul_clara',
      'moa_bath:bata_blanca',
      'moa_bath:bata_cafe',
      'moa_bath:bata_cian',
      'moa_bath:bata_gris',
      'moa_bath:bata_gris_clara',
      'moa_bath:bata_magenta',
      'moa_bath:bata_morada',
      'moa_bath:bata_naranja',
      'moa_bath:bata_negra',
      'moa_bath:bata_roja',
      'moa_bath:bata_rosa',
      'moa_bath:bata_verde',
      'moa_bath:bata_verde_lima',
    ],
    clothBoxes: [
      'moa_bath:c_toallas_amarillas',
      'moa_bath:c_toallas_azul_claras',
      'moa_bath:c_toallas_azules',
      'moa_bath:c_toallas_blancas',
      'moa_bath:c_toallas_cafes',
      'moa_bath:c_toallas_cian',
      'moa_bath:c_toallas_grises',
      'moa_bath:c_toallas_grises_claras',
      'moa_bath:c_toallas_magentas',
      'moa_bath:c_toallas_moradas',
      'moa_bath:c_toallas_natanjas',
      'moa_bath:c_toallas_negras',
      'moa_bath:c_toallas_rojas',
      'moa_bath:c_toallas_rosas',
      'moa_bath:c_toallas_verdes',
      'moa_bath:c_toallas_verdes_lima',
    ],
    clothFolded: [
      'moa_bath:toallas_amarillas',
      'moa_bath:toallas_azul',
      'moa_bath:toallas_azul_claro',
      'moa_bath:toallas_blancas',
      'moa_bath:toallas_cafes',
      'moa_bath:toallas_cian',
      'moa_bath:toallas_grises',
      'moa_bath:toallas_grises_claras',
      'moa_bath:toallas_magenta',
      'moa_bath:toallas_moradas',
      'moa_bath:toallas_naranjas',
      'moa_bath:toallas_negras',
      'moa_bath:toallas_rojas',
      'moa_bath:toallas_rosas',
      'moa_bath:toallas_verdes',
      'moa_bath:toallas_verdes_lima',
    ],
    clothHung: [
      'moa_bath:toalla_amarilla_colg',
      'moa_bath:toalla_azul_clara_colg',
      'moa_bath:toalla_azul_colg',
      'moa_bath:toalla_blanca_colg',
      'moa_bath:toalla_cafe_colg',
      'moa_bath:toalla_cian_colg',
      'moa_bath:toalla_gris_clara_colg',
      'moa_bath:toalla_gris_colg',
      'moa_bath:toalla_magenta_colg',
      'moa_bath:toalla_morada_colg',
      'moa_bath:toalla_naranja_colg',
      'moa_bath:toalla_negra_colg',
      'moa_bath:toalla_roja_colg',
      'moa_bath:toalla_rosa_colg',
      'moa_bath:toalla_verde_colg',
      'moa_bath:toalla_verde_lima_colg',
    ],
    signage: [
      'moa_bath:lb_bano_discapacitados',
      'moa_bath:lb_bano_hombres',
      'moa_bath:lb_bano_mujeres',
      'moa_bath:l_bano_discapacitados',
      'moa_bath:l_bano_hombres',
      'moa_bath:l_bano_mujeres',
      'moa_bath:letrero_piso_mojado',
    ],
    clothing: [
      'moa_bath:tabla_planchar',
      'moa_bath:tendedero_hombre',
      'moa_bath:tendedero_mujer',
      'moa_bath:tendedero_sabanas',
    ],
    general: [
      'moa_bath:barra_bano_horizontal',
      'moa_bath:barra_bano_vertical',
      'moa_bath:inodoro',
      'moa_bath:regadera',
      'moa_bath:rollos_papel_higienico',
      'moa_bath:secador_manos',
      'moa_bath:soporte_jabon',
      'moa_bath:vaso_cepillos_dientes',
      'moa_bath:trapeador',
      'moa_bath:mingitorio',
      'moa_bath:jabonera',
      'moa_bath:jaboneta_pared',
      'moa_bath:llaves_regadera',
      'moa_bath:llave_banera',
      'moa_bath:jabon',
      'moa_bath:destapa_canos',
      'moa_bath:escoba',
      'moa_bath:cubeta_agua',
      'moa_bath:esponja_bano',
      'moa_bath:lavadora',
      'moa_bath:lavadora_abierta',
      'moa_bath:papel_higienico',
      'moa_bath:plancha',
      'moa_bath:porta_papel_higienico',
      'moa_bath:banera',
      'moa_bath:lavabo',
      'moa_bath:lavabo_pedestal',
    ],
    singleMirrors: [
      'moa_bath:espejo_b',
      'moa_bath:espejo_c',
      'moa_bath:espejo_d',
      'moa_bath:espejo_n',
    ]
  },
  listCollections: {
    mirrors: [[
      'moa_bath:esp_n_izq',
      'moa_bath:espejo_n_cent',
      'moa_bath:espejo_n_der',
    ], [
      'moa_bath:espejo_b_izq',
      'moa_bath:espejo_b_cent',
      'moa_bath:espejo_b_der',
    ], [
      'moa_bath:espejo_c_izq',
      'moa_bath:espejo_c_cent',
      'moa_bath:espejo_c_der',
    ], [
      'moa_bath:espejo_d_izq',
      'moa_bath:espejo_d_cent',
      'moa_bath:espejo_d_der',
    ]]
  }
}