StartupEvents.registry('sound_event', event => {
  event.create("farming_crossing_records:oneul_april_daisy")
  event.create("farming_crossing_records:oneul_around_midnight")
  event.create("farming_crossing_records:oneul_autumn_blessing")
  event.create("farming_crossing_records:oneul_autumn_breeze")
  event.create("farming_crossing_records:oneul_brunch")
  event.create("farming_crossing_records:oneul_bubble")
  event.create("farming_crossing_records:oneul_byesummer")
  event.create("farming_crossing_records:oneul_canele")
  event.create("farming_crossing_records:oneul_cheeseburger")
  event.create("farming_crossing_records:oneul_chestnut_latte")
  event.create("farming_crossing_records:oneul_chocolate_world")
  event.create("farming_crossing_records:oneul_chuseok")
  event.create("farming_crossing_records:oneul_cloudy_rain")
  event.create("farming_crossing_records:oneul_cookie_tree")
  event.create("farming_crossing_records:oneul_dreamy")
  event.create("farming_crossing_records:oneul_flamingo")
  event.create("farming_crossing_records:oneul_floating_marshmallow")
  event.create("farming_crossing_records:oneul_full_moon")
  event.create("farming_crossing_records:oneul_get_up")
  event.create("farming_crossing_records:oneul_gift")
  event.create("farming_crossing_records:oneul_happy_reindeer")
  event.create("farming_crossing_records:oneul_joy")
  event.create("farming_crossing_records:oneul_melon_bread")
  event.create("farming_crossing_records:oneul_miracle_morning")
  event.create("farming_crossing_records:oneul_mistletoe")
  event.create("farming_crossing_records:oneul_moonlight")
  event.create("farming_crossing_records:oneul_morning_peppermint")
  event.create("farming_crossing_records:oneul_painting")
  event.create("farming_crossing_records:oneul_pajama")
  event.create("farming_crossing_records:oneul_raindrops")
  event.create("farming_crossing_records:oneul_roommate")
  event.create("farming_crossing_records:oneul_sandwich")
  event.create("farming_crossing_records:oneul_smile_peach")
  event.create("farming_crossing_records:oneul_snow_dance")
  event.create("farming_crossing_records:oneul_story")
  event.create("farming_crossing_records:oneul_strawberry_dance")
  event.create("farming_crossing_records:oneul_summer_vacation")
  event.create("farming_crossing_records:oneul_surf")
  event.create("farming_crossing_records:oneul_tiramisu")
  event.create("farming_crossing_records:oneul_umbrella")
  event.create("farming_crossing_records:oneul_vanilla_milkshake")
  event.create("farming_crossing_records:oneul_watermelon_fizz")
  event.create("farming_crossing_records:oneul_weekend_blanket")
  event.create("farming_crossing_records:oneul_winter_glow")
})

StartupEvents.registry('item', event => {
  event.create("kubejs:oneul_april_daisy")
    .jukeboxPlayable("kubejs:oneul_april_daisy", true)
    .texture("farming_crossing_records:item/oneul_april_daisy")
    .displayName("Music Disc: Oneul - April Daisy")
    .maxStackSize(64)
  event.create("kubejs:oneul_around_midnight")
    .jukeboxPlayable("kubejs:oneul_around_midnight", true)
    .texture("farming_crossing_records:item/oneul_around_midnight")
    .displayName("Music Disc: Oneul - Around Midnight")
    .maxStackSize(64)
  event.create("kubejs:oneul_autumn_blessing")
    .jukeboxPlayable("kubejs:oneul_autumn_blessing", true)
    .texture("farming_crossing_records:item/oneul_autumn_blessing")
    .displayName("Music Disc: Oneul - Autumn Blessing")
    .maxStackSize(64)
  event.create("kubejs:oneul_autumn_breeze")
    .jukeboxPlayable("kubejs:oneul_autumn_breeze", true)
    .texture("farming_crossing_records:item/oneul_autumn_breeze")
    .displayName("Music Disc: Oneul - Autumn Breeze")
    .maxStackSize(64)
  event.create("kubejs:oneul_brunch")
    .jukeboxPlayable("kubejs:oneul_brunch", true)
    .texture("farming_crossing_records:item/oneul_brunch")
    .displayName("Music Disc: Oneul - Brunch")
    .maxStackSize(64)
  event.create("kubejs:oneul_bubble")
    .jukeboxPlayable("kubejs:oneul_bubble", true)
    .texture("farming_crossing_records:item/oneul_bubble")
    .displayName("Music Disc: Oneul - Bubble")
    .maxStackSize(64)
  event.create("kubejs:oneul_byesummer")
    .jukeboxPlayable("kubejs:oneul_byesummer", true)
    .texture("farming_crossing_records:item/oneul_byesummer")
    .displayName("Music Disc: Oneul - Bye,Summer!")
    .maxStackSize(64)
  event.create("kubejs:oneul_canele")
    .jukeboxPlayable("kubejs:oneul_canele", true)
    .texture("farming_crossing_records:item/oneul_canele")
    .displayName("Music Disc: Oneul - Canelé")
    .maxStackSize(64)
  event.create("kubejs:oneul_cheeseburger")
    .jukeboxPlayable("kubejs:oneul_cheeseburger", true)
    .texture("farming_crossing_records:item/oneul_cheeseburger")
    .displayName("Music Disc: Oneul - Cheeseburger")
    .maxStackSize(64)
  event.create("kubejs:oneul_chestnut_latte")
    .jukeboxPlayable("kubejs:oneul_chestnut_latte", true)
    .texture("farming_crossing_records:item/oneul_chestnut_latte")
    .displayName("Music Disc: Oneul - Chestnut Latte")
    .maxStackSize(64)
  event.create("kubejs:oneul_chocolate_world")
    .jukeboxPlayable("kubejs:oneul_chocolate_world", true)
    .texture("farming_crossing_records:item/oneul_chocolate_world")
    .displayName("Music Disc: Oneul - Chocolate World")
    .maxStackSize(64)
  event.create("kubejs:oneul_chuseok")
    .jukeboxPlayable("kubejs:oneul_chuseok", true)
    .texture("farming_crossing_records:item/oneul_chuseok")
    .displayName("Music Disc: Oneul - Chuseok")
    .maxStackSize(64)
  event.create("kubejs:oneul_cloudy_rain")
    .jukeboxPlayable("kubejs:oneul_cloudy_rain", true)
    .texture("farming_crossing_records:item/oneul_cloudy_rain")
    .displayName("Music Disc: Oneul - Cloudy Rain")
    .maxStackSize(64)
  event.create("kubejs:oneul_cookie_tree")
    .jukeboxPlayable("kubejs:oneul_cookie_tree", true)
    .texture("farming_crossing_records:item/oneul_cookie_tree")
    .displayName("Music Disc: Oneul - Cookie Tree")
    .maxStackSize(64)
  event.create("kubejs:oneul_dreamy")
    .jukeboxPlayable("kubejs:oneul_dreamy", true)
    .texture("farming_crossing_records:item/oneul_dreamy")
    .displayName("Music Disc: Oneul - Dreamy")
    .maxStackSize(64)
  event.create("kubejs:oneul_flamingo")
    .jukeboxPlayable("kubejs:oneul_flamingo", true)
    .texture("farming_crossing_records:item/oneul_flamingo")
    .displayName("Music Disc: Oneul - Flamingo")
    .maxStackSize(64)
  event.create("kubejs:oneul_floating_marshmallow")
    .jukeboxPlayable("kubejs:oneul_floating_marshmallow", true)
    .texture("farming_crossing_records:item/oneul_floating_marshmallow")
    .displayName("Music Disc: Oneul - Floating Marshmallow")
    .maxStackSize(64)
  event.create("kubejs:oneul_full_moon")
    .jukeboxPlayable("kubejs:oneul_full_moon", true)
    .texture("farming_crossing_records:item/oneul_full_moon")
    .displayName("Music Disc: Oneul - Full Moon")
    .maxStackSize(64)
  event.create("kubejs:oneul_get_up")
    .jukeboxPlayable("kubejs:oneul_get_up", true)
    .texture("farming_crossing_records:item/oneul_get_up")
    .displayName("Music Disc: Oneul - Get up")
    .maxStackSize(64)
  event.create("kubejs:oneul_gift")
    .jukeboxPlayable("kubejs:oneul_gift", true)
    .texture("farming_crossing_records:item/oneul_gift")
    .displayName("Music Disc: Oneul - Gift")
    .maxStackSize(64)
  event.create("kubejs:oneul_happy_reindeer")
    .jukeboxPlayable("kubejs:oneul_happy_reindeer", true)
    .texture("farming_crossing_records:item/oneul_happy_reindeer")
    .displayName("Music Disc: Oneul - Happy Reindeer")
    .maxStackSize(64)
  event.create("kubejs:oneul_joy")
    .jukeboxPlayable("kubejs:oneul_joy", true)
    .texture("farming_crossing_records:item/oneul_joy")
    .displayName("Music Disc: Oneul - Joy")
    .maxStackSize(64)
  event.create("kubejs:oneul_melon_bread")
    .jukeboxPlayable("kubejs:oneul_melon_bread", true)
    .texture("farming_crossing_records:item/oneul_melon_bread")
    .displayName("Music Disc: Oneul - Melon Bread")
    .maxStackSize(64)
  event.create("kubejs:oneul_miracle_morning")
    .jukeboxPlayable("kubejs:oneul_miracle_morning", true)
    .texture("farming_crossing_records:item/oneul_miracle_morning")
    .displayName("Music Disc: Oneul - Miracle Morning")
    .maxStackSize(64)
  event.create("kubejs:oneul_mistletoe")
    .jukeboxPlayable("kubejs:oneul_mistletoe", true)
    .texture("farming_crossing_records:item/oneul_mistletoe")
    .displayName("Music Disc: Oneul - Mistletoe")
    .maxStackSize(64)
  event.create("kubejs:oneul_moonlight")
    .jukeboxPlayable("kubejs:oneul_moonlight", true)
    .texture("farming_crossing_records:item/oneul_moonlight")
    .displayName("Music Disc: Oneul - Moonlight")
    .maxStackSize(64)
  event.create("kubejs:oneul_morning_peppermint")
    .jukeboxPlayable("kubejs:oneul_morning_peppermint", true)
    .texture("farming_crossing_records:item/oneul_morning_peppermint")
    .displayName("Music Disc: Oneul - Morning Peppermint")
    .maxStackSize(64)
  event.create("kubejs:oneul_painting")
    .jukeboxPlayable("kubejs:oneul_painting", true)
    .texture("farming_crossing_records:item/oneul_painting")
    .displayName("Music Disc: Oneul - Painting")
    .maxStackSize(64)
  event.create("kubejs:oneul_pajama")
    .jukeboxPlayable("kubejs:oneul_pajama", true)
    .texture("farming_crossing_records:item/oneul_pajama")
    .displayName("Music Disc: Oneul - Pajama")
    .maxStackSize(64)
  event.create("kubejs:oneul_raindrops")
    .jukeboxPlayable("kubejs:oneul_raindrops", true)
    .texture("farming_crossing_records:item/oneul_raindrops")
    .displayName("Music Disc: Oneul - Raindrops")
    .maxStackSize(64)
  event.create("kubejs:oneul_roommate")
    .jukeboxPlayable("kubejs:oneul_roommate", true)
    .texture("farming_crossing_records:item/oneul_roommate")
    .displayName("Music Disc: Oneul - Roommate")
    .maxStackSize(64)
  event.create("kubejs:oneul_sandwich")
    .jukeboxPlayable("kubejs:oneul_sandwich", true)
    .texture("farming_crossing_records:item/oneul_sandwich")
    .displayName("Music Disc: Oneul - Sandwich")
    .maxStackSize(64)
  event.create("kubejs:oneul_smile_peach")
    .jukeboxPlayable("kubejs:oneul_smile_peach", true)
    .texture("farming_crossing_records:item/oneul_smile_peach")
    .displayName("Music Disc: Oneul - Smile Peach")
    .maxStackSize(64)
  event.create("kubejs:oneul_snow_dance")
    .jukeboxPlayable("kubejs:oneul_snow_dance", true)
    .texture("farming_crossing_records:item/oneul_snow_dance")
    .displayName("Music Disc: Oneul - Snow Dance")
    .maxStackSize(64)
  event.create("kubejs:oneul_story")
    .jukeboxPlayable("kubejs:oneul_story", true)
    .texture("farming_crossing_records:item/oneul_story")
    .displayName("Music Disc: Oneul - Story")
    .maxStackSize(64)
  event.create("kubejs:oneul_strawberry_dance")
    .jukeboxPlayable("kubejs:oneul_strawberry_dance", true)
    .texture("farming_crossing_records:item/oneul_strawberry_dance")
    .displayName("Music Disc: Oneul - Strawberry Dance")
    .maxStackSize(64)
  event.create("kubejs:oneul_summer_vacation")
    .jukeboxPlayable("kubejs:oneul_summer_vacation", true)
    .texture("farming_crossing_records:item/oneul_summer_vacation")
    .displayName("Music Disc: Oneul - Summer Vacation")
    .maxStackSize(64)
  event.create("kubejs:oneul_surf")
    .jukeboxPlayable("kubejs:oneul_surf", true)
    .texture("farming_crossing_records:item/oneul_surf")
    .displayName("Music Disc: Oneul - Surf")
    .maxStackSize(64)
  event.create("kubejs:oneul_tiramisu")
    .jukeboxPlayable("kubejs:oneul_tiramisu", true)
    .texture("farming_crossing_records:item/oneul_tiramisu")
    .displayName("Music Disc: Oneul - Tiramisu")
    .maxStackSize(64)
  event.create("kubejs:oneul_umbrella")
    .jukeboxPlayable("kubejs:oneul_umbrella", true)
    .texture("farming_crossing_records:item/oneul_umbrella")
    .displayName("Music Disc: Oneul - Umbrella")
    .maxStackSize(64)
  event.create("kubejs:oneul_vanilla_milkshake")
    .jukeboxPlayable("kubejs:oneul_vanilla_milkshake", true)
    .texture("farming_crossing_records:item/oneul_vanilla_milkshake")
    .displayName("Music Disc: Oneul - Vanilla Milkshake")
    .maxStackSize(64)
  event.create("kubejs:oneul_watermelon_fizz")
    .jukeboxPlayable("kubejs:oneul_watermelon_fizz", true)
    .texture("farming_crossing_records:item/oneul_watermelon_fizz")
    .displayName("Music Disc: Oneul - Watermelon Fizz")
    .maxStackSize(64)
  event.create("kubejs:oneul_weekend_blanket")
    .jukeboxPlayable("kubejs:oneul_weekend_blanket", true)
    .texture("farming_crossing_records:item/oneul_weekend_blanket")
    .displayName("Music Disc: Oneul - Weekend Blanket")
    .maxStackSize(64)
  event.create("kubejs:oneul_winter_glow")
    .jukeboxPlayable("kubejs:oneul_winter_glow", true)
    .texture("farming_crossing_records:item/oneul_winter_glow")
    .displayName("Music Disc: Oneul - Winter Glow")
    .maxStackSize(64)
})